openapi: 3.0.1
info:
  title: React-Express-Exercise
  description: An exercise consisting of a react client and an express server interacting with the GitHub API.
  version: 1.0.0
externalDocs:
  description: Project Sources
  url: https://github.com/benruehl/react-express-exercise
servers:
  - url: /api/v1
tags:
- name: repository
  description: Everything about GitHub repositories
paths:
  /repos:
    get:
      tags:
      - repository
      summary: Search for GitHub repositories
      operationId: getRepositories
      parameters:
      - name: q
        in: query
        description: Search expression used to query relevant repositories
        required: true
        style: form
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
  /repos/bookmarks:
    get:
      tags:
      - repository
      summary: Get all bookmarked repositories
      operationId: getBookmarkedRepositories
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Repository'
  /repos/{repoId}/bookmark:
    put:
      tags:
      - repository
      summary: Mark a repository as bookmarked
      operationId: bookmarkRepository
      parameters:
      - name: repoId
        in: path
        description: ID of repository to bookmark
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content: {}
components:
  schemas:
    Repository:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: torvalds/linux
        description:
          type: string
          example: Linux kernel source tree
        githubUrl:
          type: string
          example: https://github.com/torvalds/linux
        starsCount:
          type: integer
          format: int64
        forksCount:
          type: integer
          format: int64
